/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.agendarentrega.clients.pedido.models.EntidadeTipo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiEntidade
 */

public class ApiEntidade {
  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("tipo")
  private EntidadeTipo tipo = null;

  @SerializedName("identidadeRaiz")
  private String identidadeRaiz = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("nomeFantasia")
  private String nomeFantasia = null;

  @SerializedName("dataCadastro")
  private String dataCadastro = null;

  @SerializedName("logoPersonalizada")
  private Boolean logoPersonalizada = null;

  public ApiEntidade uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public ApiEntidade tipo(EntidadeTipo tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Get tipo
   * @return tipo
  **/
  @ApiModelProperty(value = "")
  public EntidadeTipo getTipo() {
    return tipo;
  }

  public void setTipo(EntidadeTipo tipo) {
    this.tipo = tipo;
  }

  public ApiEntidade identidadeRaiz(String identidadeRaiz) {
    this.identidadeRaiz = identidadeRaiz;
    return this;
  }

   /**
   * Get identidadeRaiz
   * @return identidadeRaiz
  **/
  @ApiModelProperty(value = "")
  public String getIdentidadeRaiz() {
    return identidadeRaiz;
  }

  public void setIdentidadeRaiz(String identidadeRaiz) {
    this.identidadeRaiz = identidadeRaiz;
  }

  public ApiEntidade nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Get nome
   * @return nome
  **/
  @ApiModelProperty(value = "")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public ApiEntidade nomeFantasia(String nomeFantasia) {
    this.nomeFantasia = nomeFantasia;
    return this;
  }

   /**
   * Get nomeFantasia
   * @return nomeFantasia
  **/
  @ApiModelProperty(value = "")
  public String getNomeFantasia() {
    return nomeFantasia;
  }

  public void setNomeFantasia(String nomeFantasia) {
    this.nomeFantasia = nomeFantasia;
  }

  public ApiEntidade dataCadastro(String dataCadastro) {
    this.dataCadastro = dataCadastro;
    return this;
  }

   /**
   * Get dataCadastro
   * @return dataCadastro
  **/
  @ApiModelProperty(value = "")
  public String getDataCadastro() {
    return dataCadastro;
  }

  public void setDataCadastro(String dataCadastro) {
    this.dataCadastro = dataCadastro;
  }

  public ApiEntidade logoPersonalizada(Boolean logoPersonalizada) {
    this.logoPersonalizada = logoPersonalizada;
    return this;
  }

   /**
   * Get logoPersonalizada
   * @return logoPersonalizada
  **/
  @ApiModelProperty(value = "")
  public Boolean isLogoPersonalizada() {
    return logoPersonalizada;
  }

  public void setLogoPersonalizada(Boolean logoPersonalizada) {
    this.logoPersonalizada = logoPersonalizada;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiEntidade apiEntidade = (ApiEntidade) o;
    return Objects.equals(this.uuid, apiEntidade.uuid) &&
        Objects.equals(this.tipo, apiEntidade.tipo) &&
        Objects.equals(this.identidadeRaiz, apiEntidade.identidadeRaiz) &&
        Objects.equals(this.nome, apiEntidade.nome) &&
        Objects.equals(this.nomeFantasia, apiEntidade.nomeFantasia) &&
        Objects.equals(this.dataCadastro, apiEntidade.dataCadastro) &&
        Objects.equals(this.logoPersonalizada, apiEntidade.logoPersonalizada);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, tipo, identidadeRaiz, nome, nomeFantasia, dataCadastro, logoPersonalizada);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiEntidade {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    identidadeRaiz: ").append(toIndentedString(identidadeRaiz)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    nomeFantasia: ").append(toIndentedString(nomeFantasia)).append("\n");
    sb.append("    dataCadastro: ").append(toIndentedString(dataCadastro)).append("\n");
    sb.append("    logoPersonalizada: ").append(toIndentedString(logoPersonalizada)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

