/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.agendarentrega.clients.pedido.models.ApiEntidade;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiFilial
 */

public class ApiFilial {
  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("identidade")
  private String identidade = null;

  @SerializedName("nome_fantasia")
  private String nomeFantasia = null;

  @SerializedName("entidade")
  private ApiEntidade entidade = null;

  public ApiFilial uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public ApiFilial identidade(String identidade) {
    this.identidade = identidade;
    return this;
  }

   /**
   * Get identidade
   * @return identidade
  **/
  @ApiModelProperty(value = "")
  public String getIdentidade() {
    return identidade;
  }

  public void setIdentidade(String identidade) {
    this.identidade = identidade;
  }

  public ApiFilial nomeFantasia(String nomeFantasia) {
    this.nomeFantasia = nomeFantasia;
    return this;
  }

   /**
   * Get nomeFantasia
   * @return nomeFantasia
  **/
  @ApiModelProperty(value = "")
  public String getNomeFantasia() {
    return nomeFantasia;
  }

  public void setNomeFantasia(String nomeFantasia) {
    this.nomeFantasia = nomeFantasia;
  }

  public ApiFilial entidade(ApiEntidade entidade) {
    this.entidade = entidade;
    return this;
  }

   /**
   * Get entidade
   * @return entidade
  **/
  @ApiModelProperty(value = "")
  public ApiEntidade getEntidade() {
    return entidade;
  }

  public void setEntidade(ApiEntidade entidade) {
    this.entidade = entidade;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiFilial apiFilial = (ApiFilial) o;
    return Objects.equals(this.uuid, apiFilial.uuid) &&
        Objects.equals(this.identidade, apiFilial.identidade) &&
        Objects.equals(this.nomeFantasia, apiFilial.nomeFantasia) &&
        Objects.equals(this.entidade, apiFilial.entidade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, identidade, nomeFantasia, entidade);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiFilial {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    identidade: ").append(toIndentedString(identidade)).append("\n");
    sb.append("    nomeFantasia: ").append(toIndentedString(nomeFantasia)).append("\n");
    sb.append("    entidade: ").append(toIndentedString(entidade)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

