/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets EntidadeTipo
 */
@JsonAdapter(EntidadeTipo.Adapter.class)
public enum EntidadeTipo {
  
  FISICA("TipoEntidade_FISICA"),
  
  JURIDICA("TipoEntidade_JURIDICA");

  private String value;

  EntidadeTipo(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EntidadeTipo fromValue(String text) {
    for (EntidadeTipo b : EntidadeTipo.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<EntidadeTipo> {
    @Override
    public void write(final JsonWriter jsonWriter, final EntidadeTipo enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EntidadeTipo read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EntidadeTipo.fromValue(String.valueOf(value));
    }
  }
}

