/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.agendarentrega.clients.pedido.models.ImportarPedidoRequestComprador;
import com.agendarentrega.clients.pedido.models.ImportarPedidoRequestEmpresa;
import com.agendarentrega.clients.pedido.models.PedidoEntrega;
import com.agendarentrega.clients.pedido.models.PedidoStatusPedido;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PedidoImportarPedidoRequest
 */

public class PedidoImportarPedidoRequest {
  @SerializedName("codigo")
  private String codigo = null;

  @SerializedName("comprador")
  private ImportarPedidoRequestComprador comprador = null;

  @SerializedName("fornecedor")
  private ImportarPedidoRequestEmpresa fornecedor = null;

  @SerializedName("emitente")
  private ImportarPedidoRequestEmpresa emitente = null;

  @SerializedName("destinatario")
  private ImportarPedidoRequestEmpresa destinatario = null;

  @SerializedName("dataEmissao")
  private String dataEmissao = null;

  @SerializedName("observacoes")
  private String observacoes = null;

  @SerializedName("entrega")
  private PedidoEntrega entrega = null;

  @SerializedName("status")
  private PedidoStatusPedido status = null;

  public PedidoImportarPedidoRequest codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

   /**
   * Get codigo
   * @return codigo
  **/
  @ApiModelProperty(value = "")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public PedidoImportarPedidoRequest comprador(ImportarPedidoRequestComprador comprador) {
    this.comprador = comprador;
    return this;
  }

   /**
   * Get comprador
   * @return comprador
  **/
  @ApiModelProperty(value = "")
  public ImportarPedidoRequestComprador getComprador() {
    return comprador;
  }

  public void setComprador(ImportarPedidoRequestComprador comprador) {
    this.comprador = comprador;
  }

  public PedidoImportarPedidoRequest fornecedor(ImportarPedidoRequestEmpresa fornecedor) {
    this.fornecedor = fornecedor;
    return this;
  }

   /**
   * Get fornecedor
   * @return fornecedor
  **/
  @ApiModelProperty(value = "")
  public ImportarPedidoRequestEmpresa getFornecedor() {
    return fornecedor;
  }

  public void setFornecedor(ImportarPedidoRequestEmpresa fornecedor) {
    this.fornecedor = fornecedor;
  }

  public PedidoImportarPedidoRequest emitente(ImportarPedidoRequestEmpresa emitente) {
    this.emitente = emitente;
    return this;
  }

   /**
   * Get emitente
   * @return emitente
  **/
  @ApiModelProperty(value = "")
  public ImportarPedidoRequestEmpresa getEmitente() {
    return emitente;
  }

  public void setEmitente(ImportarPedidoRequestEmpresa emitente) {
    this.emitente = emitente;
  }

  public PedidoImportarPedidoRequest destinatario(ImportarPedidoRequestEmpresa destinatario) {
    this.destinatario = destinatario;
    return this;
  }

   /**
   * Get destinatario
   * @return destinatario
  **/
  @ApiModelProperty(value = "")
  public ImportarPedidoRequestEmpresa getDestinatario() {
    return destinatario;
  }

  public void setDestinatario(ImportarPedidoRequestEmpresa destinatario) {
    this.destinatario = destinatario;
  }

  public PedidoImportarPedidoRequest dataEmissao(String dataEmissao) {
    this.dataEmissao = dataEmissao;
    return this;
  }

   /**
   * Get dataEmissao
   * @return dataEmissao
  **/
  @ApiModelProperty(value = "")
  public String getDataEmissao() {
    return dataEmissao;
  }

  public void setDataEmissao(String dataEmissao) {
    this.dataEmissao = dataEmissao;
  }

  public PedidoImportarPedidoRequest observacoes(String observacoes) {
    this.observacoes = observacoes;
    return this;
  }

   /**
   * Get observacoes
   * @return observacoes
  **/
  @ApiModelProperty(value = "")
  public String getObservacoes() {
    return observacoes;
  }

  public void setObservacoes(String observacoes) {
    this.observacoes = observacoes;
  }

  public PedidoImportarPedidoRequest entrega(PedidoEntrega entrega) {
    this.entrega = entrega;
    return this;
  }

   /**
   * Get entrega
   * @return entrega
  **/
  @ApiModelProperty(value = "")
  public PedidoEntrega getEntrega() {
    return entrega;
  }

  public void setEntrega(PedidoEntrega entrega) {
    this.entrega = entrega;
  }

  public PedidoImportarPedidoRequest status(PedidoStatusPedido status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public PedidoStatusPedido getStatus() {
    return status;
  }

  public void setStatus(PedidoStatusPedido status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PedidoImportarPedidoRequest pedidoImportarPedidoRequest = (PedidoImportarPedidoRequest) o;
    return Objects.equals(this.codigo, pedidoImportarPedidoRequest.codigo) &&
        Objects.equals(this.comprador, pedidoImportarPedidoRequest.comprador) &&
        Objects.equals(this.fornecedor, pedidoImportarPedidoRequest.fornecedor) &&
        Objects.equals(this.emitente, pedidoImportarPedidoRequest.emitente) &&
        Objects.equals(this.destinatario, pedidoImportarPedidoRequest.destinatario) &&
        Objects.equals(this.dataEmissao, pedidoImportarPedidoRequest.dataEmissao) &&
        Objects.equals(this.observacoes, pedidoImportarPedidoRequest.observacoes) &&
        Objects.equals(this.entrega, pedidoImportarPedidoRequest.entrega) &&
        Objects.equals(this.status, pedidoImportarPedidoRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, comprador, fornecedor, emitente, destinatario, dataEmissao, observacoes, entrega, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PedidoImportarPedidoRequest {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    comprador: ").append(toIndentedString(comprador)).append("\n");
    sb.append("    fornecedor: ").append(toIndentedString(fornecedor)).append("\n");
    sb.append("    emitente: ").append(toIndentedString(emitente)).append("\n");
    sb.append("    destinatario: ").append(toIndentedString(destinatario)).append("\n");
    sb.append("    dataEmissao: ").append(toIndentedString(dataEmissao)).append("\n");
    sb.append("    observacoes: ").append(toIndentedString(observacoes)).append("\n");
    sb.append("    entrega: ").append(toIndentedString(entrega)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

