/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.agendarentrega.clients.pedido.models.PedidoStatusPedido;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PedidoAlterarStatusPedidoRequest
 */

public class PedidoAlterarStatusPedidoRequest {
  @SerializedName("cnpjEmitente")
  private String cnpjEmitente = null;

  @SerializedName("codigo")
  private String codigo = null;

  @SerializedName("status")
  private PedidoStatusPedido status = null;

  public PedidoAlterarStatusPedidoRequest cnpjEmitente(String cnpjEmitente) {
    this.cnpjEmitente = cnpjEmitente;
    return this;
  }

   /**
   * Get cnpjEmitente
   * @return cnpjEmitente
  **/
  @ApiModelProperty(value = "")
  public String getCnpjEmitente() {
    return cnpjEmitente;
  }

  public void setCnpjEmitente(String cnpjEmitente) {
    this.cnpjEmitente = cnpjEmitente;
  }

  public PedidoAlterarStatusPedidoRequest codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

   /**
   * Get codigo
   * @return codigo
  **/
  @ApiModelProperty(value = "")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public PedidoAlterarStatusPedidoRequest status(PedidoStatusPedido status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public PedidoStatusPedido getStatus() {
    return status;
  }

  public void setStatus(PedidoStatusPedido status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PedidoAlterarStatusPedidoRequest pedidoAlterarStatusPedidoRequest = (PedidoAlterarStatusPedidoRequest) o;
    return Objects.equals(this.cnpjEmitente, pedidoAlterarStatusPedidoRequest.cnpjEmitente) &&
        Objects.equals(this.codigo, pedidoAlterarStatusPedidoRequest.codigo) &&
        Objects.equals(this.status, pedidoAlterarStatusPedidoRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cnpjEmitente, codigo, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PedidoAlterarStatusPedidoRequest {\n");
    
    sb.append("    cnpjEmitente: ").append(toIndentedString(cnpjEmitente)).append("\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

