/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.agendarentrega.clients.pedido.models.PedidoPedido;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PedidoGetPedidoDestinatarioByEntidadeFornecedorResponse
 */

public class PedidoGetPedidoDestinatarioByEntidadeFornecedorResponse {
  @SerializedName("pedidos")
  private List<PedidoPedido> pedidos = null;

  public PedidoGetPedidoDestinatarioByEntidadeFornecedorResponse pedidos(List<PedidoPedido> pedidos) {
    this.pedidos = pedidos;
    return this;
  }

  public PedidoGetPedidoDestinatarioByEntidadeFornecedorResponse addPedidosItem(PedidoPedido pedidosItem) {
    if (this.pedidos == null) {
      this.pedidos = new ArrayList<PedidoPedido>();
    }
    this.pedidos.add(pedidosItem);
    return this;
  }

   /**
   * Get pedidos
   * @return pedidos
  **/
  @ApiModelProperty(value = "")
  public List<PedidoPedido> getPedidos() {
    return pedidos;
  }

  public void setPedidos(List<PedidoPedido> pedidos) {
    this.pedidos = pedidos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PedidoGetPedidoDestinatarioByEntidadeFornecedorResponse pedidoGetPedidoDestinatarioByEntidadeFornecedorResponse = (PedidoGetPedidoDestinatarioByEntidadeFornecedorResponse) o;
    return Objects.equals(this.pedidos, pedidoGetPedidoDestinatarioByEntidadeFornecedorResponse.pedidos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pedidos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PedidoGetPedidoDestinatarioByEntidadeFornecedorResponse {\n");
    
    sb.append("    pedidos: ").append(toIndentedString(pedidos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

