/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PedidoStatusEntidadeResponse
 */

public class PedidoStatusEntidadeResponse {
  @SerializedName("ativo")
  private Boolean ativo = null;

  @SerializedName("importacaoAtiva")
  private Boolean importacaoAtiva = null;

  public PedidoStatusEntidadeResponse ativo(Boolean ativo) {
    this.ativo = ativo;
    return this;
  }

   /**
   * Get ativo
   * @return ativo
  **/
  @ApiModelProperty(value = "")
  public Boolean isAtivo() {
    return ativo;
  }

  public void setAtivo(Boolean ativo) {
    this.ativo = ativo;
  }

  public PedidoStatusEntidadeResponse importacaoAtiva(Boolean importacaoAtiva) {
    this.importacaoAtiva = importacaoAtiva;
    return this;
  }

   /**
   * Get importacaoAtiva
   * @return importacaoAtiva
  **/
  @ApiModelProperty(value = "")
  public Boolean isImportacaoAtiva() {
    return importacaoAtiva;
  }

  public void setImportacaoAtiva(Boolean importacaoAtiva) {
    this.importacaoAtiva = importacaoAtiva;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PedidoStatusEntidadeResponse pedidoStatusEntidadeResponse = (PedidoStatusEntidadeResponse) o;
    return Objects.equals(this.ativo, pedidoStatusEntidadeResponse.ativo) &&
        Objects.equals(this.importacaoAtiva, pedidoStatusEntidadeResponse.importacaoAtiva);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ativo, importacaoAtiva);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PedidoStatusEntidadeResponse {\n");
    
    sb.append("    ativo: ").append(toIndentedString(ativo)).append("\n");
    sb.append("    importacaoAtiva: ").append(toIndentedString(importacaoAtiva)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

