/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets pedidoStatusPedido
 */
@JsonAdapter(PedidoStatusPedido.Adapter.class)
public enum PedidoStatusPedido {
  
  STATUS_PEDIDO_INDEFINIDO("STATUS_PEDIDO_INDEFINIDO"),
  
  PEDIDO_EM_ABERTO("PEDIDO_EM_ABERTO"),
  
  PEDIDO_CONCLUIDO("PEDIDO_CONCLUIDO");

  private String value;

  PedidoStatusPedido(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PedidoStatusPedido fromValue(String text) {
    for (PedidoStatusPedido b : PedidoStatusPedido.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PedidoStatusPedido> {
    @Override
    public void write(final JsonWriter jsonWriter, final PedidoStatusPedido enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PedidoStatusPedido read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PedidoStatusPedido.fromValue(String.valueOf(value));
    }
  }
}

