/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.agendarentrega.clients.pedido.models.PedidoPedido;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PedidoImportarPedidoResponse
 */

public class PedidoImportarPedidoResponse {
  @SerializedName("pedido")
  private PedidoPedido pedido = null;

  public PedidoImportarPedidoResponse pedido(PedidoPedido pedido) {
    this.pedido = pedido;
    return this;
  }

   /**
   * Get pedido
   * @return pedido
  **/
  @ApiModelProperty(value = "")
  public PedidoPedido getPedido() {
    return pedido;
  }

  public void setPedido(PedidoPedido pedido) {
    this.pedido = pedido;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PedidoImportarPedidoResponse pedidoImportarPedidoResponse = (PedidoImportarPedidoResponse) o;
    return Objects.equals(this.pedido, pedidoImportarPedidoResponse.pedido);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pedido);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PedidoImportarPedidoResponse {\n");
    
    sb.append("    pedido: ").append(toIndentedString(pedido)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

