/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.agendarentrega.clients.pedido.models.AccountUserProfile;
import com.agendarentrega.clients.pedido.models.ApiFilial;
import com.agendarentrega.clients.pedido.models.PedidoEntrega;
import com.agendarentrega.clients.pedido.models.PedidoStatusPedido;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PedidoPedido
 */

public class PedidoPedido {
  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("codigo")
  private String codigo = null;

  @SerializedName("comprador")
  private AccountUserProfile comprador = null;

  @SerializedName("fornecedor")
  private ApiFilial fornecedor = null;

  @SerializedName("emitente")
  private ApiFilial emitente = null;

  @SerializedName("destinatario")
  private ApiFilial destinatario = null;

  @SerializedName("dataCadastro")
  private String dataCadastro = null;

  @SerializedName("dataEmissao")
  private String dataEmissao = null;

  @SerializedName("observacoes")
  private String observacoes = null;

  @SerializedName("entrega")
  private PedidoEntrega entrega = null;

  @SerializedName("status")
  private PedidoStatusPedido status = null;

  public PedidoPedido uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public PedidoPedido codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

   /**
   * Get codigo
   * @return codigo
  **/
  @ApiModelProperty(value = "")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public PedidoPedido comprador(AccountUserProfile comprador) {
    this.comprador = comprador;
    return this;
  }

   /**
   * Get comprador
   * @return comprador
  **/
  @ApiModelProperty(value = "")
  public AccountUserProfile getComprador() {
    return comprador;
  }

  public void setComprador(AccountUserProfile comprador) {
    this.comprador = comprador;
  }

  public PedidoPedido fornecedor(ApiFilial fornecedor) {
    this.fornecedor = fornecedor;
    return this;
  }

   /**
   * Get fornecedor
   * @return fornecedor
  **/
  @ApiModelProperty(value = "")
  public ApiFilial getFornecedor() {
    return fornecedor;
  }

  public void setFornecedor(ApiFilial fornecedor) {
    this.fornecedor = fornecedor;
  }

  public PedidoPedido emitente(ApiFilial emitente) {
    this.emitente = emitente;
    return this;
  }

   /**
   * Get emitente
   * @return emitente
  **/
  @ApiModelProperty(value = "")
  public ApiFilial getEmitente() {
    return emitente;
  }

  public void setEmitente(ApiFilial emitente) {
    this.emitente = emitente;
  }

  public PedidoPedido destinatario(ApiFilial destinatario) {
    this.destinatario = destinatario;
    return this;
  }

   /**
   * Get destinatario
   * @return destinatario
  **/
  @ApiModelProperty(value = "")
  public ApiFilial getDestinatario() {
    return destinatario;
  }

  public void setDestinatario(ApiFilial destinatario) {
    this.destinatario = destinatario;
  }

  public PedidoPedido dataCadastro(String dataCadastro) {
    this.dataCadastro = dataCadastro;
    return this;
  }

   /**
   * Get dataCadastro
   * @return dataCadastro
  **/
  @ApiModelProperty(value = "")
  public String getDataCadastro() {
    return dataCadastro;
  }

  public void setDataCadastro(String dataCadastro) {
    this.dataCadastro = dataCadastro;
  }

  public PedidoPedido dataEmissao(String dataEmissao) {
    this.dataEmissao = dataEmissao;
    return this;
  }

   /**
   * Get dataEmissao
   * @return dataEmissao
  **/
  @ApiModelProperty(value = "")
  public String getDataEmissao() {
    return dataEmissao;
  }

  public void setDataEmissao(String dataEmissao) {
    this.dataEmissao = dataEmissao;
  }

  public PedidoPedido observacoes(String observacoes) {
    this.observacoes = observacoes;
    return this;
  }

   /**
   * Get observacoes
   * @return observacoes
  **/
  @ApiModelProperty(value = "")
  public String getObservacoes() {
    return observacoes;
  }

  public void setObservacoes(String observacoes) {
    this.observacoes = observacoes;
  }

  public PedidoPedido entrega(PedidoEntrega entrega) {
    this.entrega = entrega;
    return this;
  }

   /**
   * Get entrega
   * @return entrega
  **/
  @ApiModelProperty(value = "")
  public PedidoEntrega getEntrega() {
    return entrega;
  }

  public void setEntrega(PedidoEntrega entrega) {
    this.entrega = entrega;
  }

  public PedidoPedido status(PedidoStatusPedido status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public PedidoStatusPedido getStatus() {
    return status;
  }

  public void setStatus(PedidoStatusPedido status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PedidoPedido pedidoPedido = (PedidoPedido) o;
    return Objects.equals(this.uuid, pedidoPedido.uuid) &&
        Objects.equals(this.codigo, pedidoPedido.codigo) &&
        Objects.equals(this.comprador, pedidoPedido.comprador) &&
        Objects.equals(this.fornecedor, pedidoPedido.fornecedor) &&
        Objects.equals(this.emitente, pedidoPedido.emitente) &&
        Objects.equals(this.destinatario, pedidoPedido.destinatario) &&
        Objects.equals(this.dataCadastro, pedidoPedido.dataCadastro) &&
        Objects.equals(this.dataEmissao, pedidoPedido.dataEmissao) &&
        Objects.equals(this.observacoes, pedidoPedido.observacoes) &&
        Objects.equals(this.entrega, pedidoPedido.entrega) &&
        Objects.equals(this.status, pedidoPedido.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, codigo, comprador, fornecedor, emitente, destinatario, dataCadastro, dataEmissao, observacoes, entrega, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PedidoPedido {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    comprador: ").append(toIndentedString(comprador)).append("\n");
    sb.append("    fornecedor: ").append(toIndentedString(fornecedor)).append("\n");
    sb.append("    emitente: ").append(toIndentedString(emitente)).append("\n");
    sb.append("    destinatario: ").append(toIndentedString(destinatario)).append("\n");
    sb.append("    dataCadastro: ").append(toIndentedString(dataCadastro)).append("\n");
    sb.append("    dataEmissao: ").append(toIndentedString(dataEmissao)).append("\n");
    sb.append("    observacoes: ").append(toIndentedString(observacoes)).append("\n");
    sb.append("    entrega: ").append(toIndentedString(entrega)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

