/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets UserAuthenticationMethod
 */
@JsonAdapter(UserAuthenticationMethod.Adapter.class)
public enum UserAuthenticationMethod {
  
  NONE("AuthenticationMethod_NONE"),
  
  USERNAME("AuthenticationMethod_USERNAME"),
  
  EMAIL("AuthenticationMethod_EMAIL");

  private String value;

  UserAuthenticationMethod(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UserAuthenticationMethod fromValue(String text) {
    for (UserAuthenticationMethod b : UserAuthenticationMethod.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<UserAuthenticationMethod> {
    @Override
    public void write(final JsonWriter jsonWriter, final UserAuthenticationMethod enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public UserAuthenticationMethod read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return UserAuthenticationMethod.fromValue(String.valueOf(value));
    }
  }
}

