/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.service;

import com.agendarentrega.clients.pedido.invoker.ApiException;
import com.agendarentrega.clients.pedido.models.PedidoStatusEntidadeResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EntidadeServiceApi
 */
@Ignore
public class EntidadeServiceApiTest {

    private final EntidadeServiceApi api = new EntidadeServiceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void statusEntidadeTest() throws ApiException {
        String entidadeUUID = null;
        PedidoStatusEntidadeResponse response = api.statusEntidade(entidadeUUID);

        // TODO: test validations
    }
    
}
