/*
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.agendarentrega.clients.pedido.service;

import com.agendarentrega.clients.pedido.invoker.ApiException;
import com.agendarentrega.clients.pedido.models.PedidoAlterarStatusPedidoRequest;
import com.agendarentrega.clients.pedido.models.PedidoAlterarStatusPedidoResponse;
import com.agendarentrega.clients.pedido.models.PedidoImportarPedidoRequest;
import com.agendarentrega.clients.pedido.models.PedidoImportarPedidoResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PedidoServiceApi
 */
@Ignore
public class PedidoServiceApiTest {

    private final PedidoServiceApi api = new PedidoServiceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void alterarStatusPedidoTest() throws ApiException {
        String cnpjEmitente = null;
        String codigo = null;
        PedidoAlterarStatusPedidoRequest body = null;
        PedidoAlterarStatusPedidoResponse response = api.alterarStatusPedido(cnpjEmitente, codigo, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importarPedidoTest() throws ApiException {
        PedidoImportarPedidoRequest body = null;
        PedidoImportarPedidoResponse response = api.importarPedido(body);

        // TODO: test validations
    }
    
}
